### ISSUE TITLE
Request: cross platform support

### ISSUE THREAD

**Issue by calebcartwright** [mmajcica/retain-release#1]
I love the functionality provided by this extension. It's something we've been doing manually for a while so the capability will be great for us. However, the current Powershell implementation can only be executed on a Windows-based agent. 

Would you consider adding a Node.js implementation of this task which the VSTS agent could run on any platform, regardless of OS?

**Comment by mmajcica** [comment]
@calebcartwright I have a version of it written in ts/node. Give me a couple of days to package it and update the documentation.

**Comment by calebcartwright** [comment]
awesome!

**Comment by mmajcica** [comment]
You can find the new version on Marketplace [https://marketplace.visualstudio.com/items?itemName=mmajcica.retain-release](https://marketplace.visualstudio.com/items?itemName=mmajcica.retain-release).

Would you be so gentle to test it on a non windows agent?

Thanks

**Comment by calebcartwright** [comment]
will do so shortly

**Comment by calebcartwright** [comment]
looks good on Mac and Linux! thanks for the quick turn around 👍
