### ISSUE TITLE
ADO permissions have changed?

### ISSUE THREAD

**Issue by jpurrTTC** [mmajcica/retain-release#10]
Getting this error again: VS402904: Access denied: User Project Collection Build Service (xxxxxxxxx) does not have manage releases permission. Contact your release manager.

But 'manage releases' is no longer an option to enable. The options are now:
Bypass policies when completing pull requests
Bypass policies when pushing
Contribute
Contribute to pull requests
Create branch
Create repository
Create tag
Delete repository
Edit policies
Force push (rewrite history, delete branches and tags)
Manage notes
Manage permissions
Read
Remove others' locks
Rename repository

Please advise.
Thanks

**Comment by mmajcica** [comment]
I still see it, select your release and edit the Security

![image](https://user-images.githubusercontent.com/3026551/85564781-d5cdb300-b62e-11ea-93ae-7181e0d3628a.png)

Then I can still see it there:
![image](https://user-images.githubusercontent.com/3026551/85565066-14636d80-b62f-11ea-9159-498c03fd8599.png)
