### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by Shahyads** [mmajcica/retain-release#4]
We have configured https for tfs 2018 on premise. its ssl certificate is local. so when running this task we get the following error message:
"unable to get local issuer certificate"

**Comment by Shahyads** [comment]
I found the solution just set the variable Agent.SkipCertValidation=true

**Comment by mmajcica** [comment]
Hi,

indeed, you can disable the ssl check in that way. I'm using the vsts-node-api for all of the calls to VSTS and you can check here how some of the options are passed in:
https://github.com/Microsoft/vsts-node-api/blob/1dc7a4af55e588ed7143b7bb563fb92ba385f291/api/WebApi.ts#L123

Also you could get/set a caCert file in the same way on your agent and import the certificate in it.

Based on this feedback I may add an extra option to ignore ssl cert on the task itself.

**Comment by mmajcica** [comment]
On that, check if Agent.ClientCertArchive is pointing to any file if not, you could set that to point to a cacert file of your choice that contains your certificate.

**Comment by Shahyads** [comment]
actually the environment variable "Agent_CAInfo" can be set to the path of the certificates file 
something like this 
set Agent_CAInfo=E:\TFSAgents\ca-bundle.crt 

where ca-bundle.crt file contains the azure devops server (tfs) certificate
